# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-07 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.TextField(default='state_new', verbose_name='موقعیت')),
                ('state_description', models.CharField(default='جدید', max_length=200, verbose_name='توضیح موقعیت')),
            ],
            options={
                'verbose_name': 'موقعیت در ربات',
                'verbose_name_plural': 'موقعیت در ربات',
            },
        ),
        migrations.CreateModel(
            name='TelegramText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_get', models.TextField(verbose_name='متن')),
            ],
            options={
                'verbose_name': 'متن های عمومی ربات',
                'verbose_name_plural': 'متن های عمومی ربات',
            },
        ),
        migrations.CreateModel(
            name='TelegramTextCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_get', models.TextField(verbose_name='دسته')),
            ],
            options={
                'verbose_name': 'دسته بندی عمومی متون',
                'verbose_name_plural': 'دسته بندی عمومی متون',
            },
        ),
        migrations.AddField(
            model_name='telegramtext',
            name='category_get',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot_text_list.TelegramTextCategory', verbose_name='دسته بندی'),
        ),
    ]
