# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-07 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(default='سوالات مشتری', max_length=200, verbose_name='بخش')),
                ('category_name', models.CharField(max_length=200, verbose_name='نام دسته')),
                ('category_description', models.CharField(default='بدون توضیح', max_length=2000, verbose_name='توضیحات')),
                ('category_priority', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30')], max_length=100, verbose_name='اولویت')),
                ('createdTime', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('changedTime', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
            ],
            options={
                'verbose_name': 'دسته بندی موضوعی مشتریان',
                'verbose_name_plural': 'دسته بندی موضوعی مشتریان',
            },
        ),
        migrations.CreateModel(
            name='CustomerQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=200, verbose_name='عنوان سوال')),
                ('question_answer', models.CharField(max_length=2000, verbose_name='پاسخ سوال')),
                ('question_priority', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30')], max_length=100, verbose_name='اولویت')),
                ('createdTime', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('changedTime', models.DateTimeField(auto_now=True, verbose_name='زمان تغییر')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telehelp_app.CustomerCategory', verbose_name='انتخاب دسته')),
            ],
            options={
                'verbose_name': 'سوالات مشتریان',
                'verbose_name_plural': 'سوالات مشتریان',
            },
        ),
        migrations.CreateModel(
            name='ProviderCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(default='سوالات سرویس دهنده', max_length=200, verbose_name='بخش')),
                ('category_name', models.CharField(max_length=200, verbose_name='نام دسته')),
                ('category_description', models.CharField(default='بدون توضیح', max_length=2000, verbose_name='توضیحات')),
                ('category_priority', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30')], max_length=100, verbose_name='اولویت')),
                ('createdTime', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('changedTime', models.DateTimeField(auto_now=True, verbose_name='زمان تغییر')),
            ],
            options={
                'verbose_name': 'دسته بندی موضوعی سرویس دهندگان',
                'verbose_name_plural': 'دسته بندی موضوعی سرویس دهندگان',
            },
        ),
        migrations.CreateModel(
            name='ProviderQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=200, verbose_name='عنوان سوال')),
                ('question_answer', models.CharField(max_length=2000, verbose_name='پاسخ سوال')),
                ('question_priority', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30')], max_length=100, verbose_name='اولویت')),
                ('createdTime', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('changedTime', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telehelp_app.ProviderCategory', verbose_name='انتخاب دسته')),
            ],
            options={
                'verbose_name': 'سوالات سرویس دهندگان',
                'verbose_name_plural': 'سوالات سرویس دهندگان',
            },
        ),
        migrations.CreateModel(
            name='StartMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=200, verbose_name='منو')),
                ('category_priority', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30')], max_length=100, verbose_name='اولویت')),
                ('createdTime', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('changedTime', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
            ],
            options={
                'verbose_name': 'صفحه اصلی',
                'verbose_name_plural': 'صفحه اصلی',
            },
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, unique=True, verbose_name='کد کاربری تلگرام')),
                ('username', models.CharField(max_length=50, verbose_name='نام انتخابی کاربر')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام کاربر')),
                ('last_name', models.CharField(max_length=50, verbose_name='فامیل کاربر')),
                ('createdUserTime', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت اکانت')),
                ('changedUserTime', models.DateTimeField(auto_now=True, verbose_name='آخرین استفاده از ربات')),
                ('status', models.CharField(choices=[('فعال', 'فعال'), ('غیرفعال', 'غیرفعال')], default='فعال', max_length=200, verbose_name='وضعیت کاربر')),
                ('state', models.CharField(default='جدید', max_length=200, verbose_name='موقعیت در ربات')),
                ('account_type', models.CharField(choices=[('ناظر', 'ناظر'), ('کاربر عادی', 'کاربر عادی')], default='کاربر عادی', max_length=200, verbose_name='نوع اکانت')),
            ],
            options={
                'verbose_name': 'کاربران تلگرام بات',
                'verbose_name_plural': 'کاربران تلگرام بات',
            },
        ),
        migrations.CreateModel(
            name='UsersAsk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, verbose_name='کد کاربری تلگرام')),
                ('username', models.CharField(blank=True, max_length=200, null=True, verbose_name='کد کاربری شخصی')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='فامیل')),
                ('ask_text', models.TextField(verbose_name='متن انتقاد و پیشنهاد')),
                ('ask_time', models.DateTimeField(auto_now=True, verbose_name='زمان انتقاد و پیشنهاد')),
                ('ask_state', models.CharField(choices=[('پاسخ داده\u200cنشده', 'پاسخ داده\u200cنشده'), ('پاسخ داده\u200cشده', 'پاسخ داده\u200cشده')], default='پاسخ داده نشده', max_length=200, verbose_name='وضعیت')),
                ('ask_category', models.CharField(choices=[('مشتری', 'مشتری'), ('سرویس\u200cدهنده', 'سرویس\u200cدهنده')], max_length=200, verbose_name='نوع کاربر')),
            ],
            options={
                'verbose_name': 'سوالات از استادکار',
                'verbose_name_plural': 'سوالات از استادکار',
            },
        ),
        migrations.CreateModel(
            name='UsersLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, verbose_name='کد کاربری تلگرام')),
                ('user_log_data', models.TextField(verbose_name='لاگ کاربر')),
                ('user_log_time', models.DateTimeField(auto_now=True, verbose_name='زمان لاگ')),
                ('user_log_message_id', models.CharField(max_length=100, verbose_name='شماره پیام')),
            ],
            options={
                'verbose_name': 'لاگ های کاربران',
                'verbose_name_plural': 'لاگ های کاربران',
            },
        ),
        migrations.CreateModel(
            name='UsersOpinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_opinion_id', models.CharField(max_length=20, verbose_name='کد کاربری تلگرام')),
                ('username', models.CharField(blank=True, max_length=200, null=True, verbose_name='کد کاربری شخصی')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='فامیل')),
                ('user_opinion_text', models.TextField(verbose_name='متن انتقاد و پیشنهاد')),
                ('user_opinion_time', models.DateTimeField(auto_now=True, verbose_name='زمان انتقاد و پیشنهاد')),
                ('opinion_state', models.CharField(choices=[('دیده نشده', 'دیده نشده'), ('دیده شده', 'دیده شده'), ('قبول شده', 'قبول شده'), ('رد شده', 'رد شده'), ('انجام شده', 'انجام شده')], default='دیده نشده', max_length=200, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'انتقادها و پیشنهادها',
                'verbose_name_plural': 'انتقادها و پیشنهادها',
            },
        ),
    ]
